### PR TITLE
Bump to 0.13.2

### PR DESCRIPTION
**Pull request by agatheblues**

### CODE REVIEW

**Review by andreasknoepfle — APPROVED** [review]
Looks good. Can you check why the CI fails?

**Comment by agatheblues** [comment]
> Looks good. Can you check why the CI fails?

CircleCI can't checkout the repo. The deploy key is gone from github's project settings!

**Comment by andreasknoepfle** [comment]
Can we recreate it?

**Comment by andreasknoepfle** [comment]
Alternatively move to github actions with this :)

**Pull request merged**
