### PR TITLE
Add :error_tag option to Repo.fetch_by/3.

### PR DESCRIPTION
**Pull request by maltoe**

### CODE REVIEW

**Comment by agatheblues** [comment]
Nice 🍬

**Review by agatheblues — APPROVED** [review]

**Comment by agatheblues** [comment]
Sorry, I thought I approved back then!

**Comment by maltoe** [comment]
> Sorry, I thought I approved back then!

No worries. Do we want this? I thought you had some PR where you needed it? What happened to it?

**Comment by maltoe** [comment]
:shrug: purchase complete

**Comment by agatheblues** [comment]
I merged the PR where I needed it and added a tech wishlist ticket for when this is released

**Pull request merged**
